# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Package Builder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Determine architecture
        id: arch
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "arch=x86_64" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "arch=$(uname -m)" >> $GITHUB_ENV
          else
            echo "arch=$(uname -m)" >> $GITHUB_ENV
          fi
    
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.11'
          spec: 'software/assembler/main.py'
          requirements: 'software/assembler/requirements.txt'
          upload_exe_with_name: 'assembler_${{ env.arch }}'
          options: --onefile, --name "assembler",
